import 'package:flutter_test/flutter_test.dart';
import 'package:scansafe/core/fuzzy.dart';
import 'package:scansafe/core/risk_level.dart';
import 'package:scansafe/core/url_scorer.dart';

/// GENERATED by tool/generate_parity_test.py — do not edit by hand.
///
/// Ground truth comes from the Python research prototype
/// (scansafe_prototype.py), scored with a freshly cleared SimHash cache, plus
/// the deliberate divergences recorded in tool/generate_parity_corpus.py.
/// Each row is (url, expectedScore, expectedLevel, firedRules).
///
/// A failure here means the Dart engine drifted from the research artefact.
/// Fix the engine. Regenerating the corpus to turn a test green destroys the
/// evidence instead of the bug.
const List<(String, int, String, List<int>)> parityCorpus = [
  ('https://google.com', 0, 'SAFE', []),
  ('example.com', 0, 'SAFE', []),
  ('http://example.com', 2, 'SAFE', [1]),
  ('http://192.168.1.1/login', 8, 'HIGH RISK', [1, 2, 16, 17]),
  ('https://free-gift.xyz', 2, 'SAFE', [3]),
  ('https://news.ru', 1, 'SAFE', [4]),
  ('https://a.b.c.d.e.example.com', 2, 'SAFE', [5]),
  ('https://example.com/seg/seg/seg/seg/seg/seg/seg/seg/seg/seg/seg/seg/seg/seg/seg/seg/seg/seg/seg/seg/', 1, 'SAFE', [6]),
  ('https://example.com/p?a=1&b=2&c=3&d=4&e=5&f=6', 1, 'SAFE', [7]),
  ('https://paypal.fakesite.com', 3, 'SUSPICIOUS', [8]),
  ('https://bit.ly/3xAbCd', 2, 'SAFE', [9]),
  ('https://example.com@evil.com/path', 3, 'SUSPICIOUS', [10]),
  ('https://xn--80ak6aa92e.com', 4, 'SUSPICIOUS', [11, 16]),
  ('https://example.com/invoice.pdf.exe', 2, 'SAFE', [12]),
  ('https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fevil.tk%2Flogin', 14, 'HIGH RISK', [5, 13, 17, 18]),
  ('javascript:alert(1)', 8, 'HIGH RISK', [14, 21]),
  ('blob:https://evil.com/2f8a-uuid', 6, 'HIGH RISK', [14]),
  ('data:text/html,hello', 6, 'HIGH RISK', [14]),
  ('https://xkcdvbnmqz.com', 1, 'SAFE', [15]),
  ('https://abc123456.com', 1, 'SAFE', [16]),
  ('https://example.com/login', 2, 'SAFE', [17]),
  ('https://example.com/p?x=%41%42%43%44%45', 1, 'SAFE', [18]),
  ('https://paypa1.com', 3, 'SUSPICIOUS', [19]),
  ('https://grarnbling.edu', 4, 'SUSPICIOUS', [15, 19]),
  ('https://arnazon.com', 0, 'SAFE', []),
  ('https://ivoryrobinson94.wixsite.com/0ne-dr1ve', 6, 'HIGH RISK', [19, 22]),
  ('https://example.com/verify-now', 4, 'SUSPICIOUS', [17, 21]),
  ('https://acm-grambling.github.io', 0, 'SAFE', []),
  ('https://acm-grambling.github.io/events', 0, 'SAFE', []),
  ('https://docs.google.com/document/d/abc', 0, 'SAFE', []),
  ('https://grambling.edu', 1, 'SAFE', [15]),
  ('https://secure-chase-login.tk/account/verify', 7, 'HIGH RISK', [3, 8, 17]),
  ('https://my.site.vercel.app/paypa1', 6, 'HIGH RISK', [19, 22]),
  ('https://tinyurl.com/abcd', 2, 'SAFE', [9]),
  ('http://10.0.0.5:8080/admin/password', 7, 'HIGH RISK', [1, 2, 17]),
  ('https://office365-login.click/auth?token=abc', 8, 'HIGH RISK', [3, 8, 16, 17]),
  ('https://www.grambling.edu/admissions', 0, 'SAFE', []),
  ('https://www.instagram.com', 0, 'SAFE', []),
  ('https://www.grambling.edu/academics/colleges/college-of-business', 0, 'SAFE', []),
  ('https://grarnbling.edu/student/login', 6, 'HIGH RISK', [15, 17, 19]),
  ('http://xn--pypal-4ve.xyz/signin/verify?action=urgent', 12, 'HIGH RISK', [1, 3, 11, 15, 17, 21]),
];

void main() {
  group('Dart engine matches the Python prototype', () {
    for (final (url, expectedScore, expectedLevel, expectedRules)
        in parityCorpus) {
      test('scores $url as $expectedScore ($expectedLevel)', () {
        // Fresh scorer per case mirrors clearing the prototype's global
        // SimHash cache, so Rule 20 cannot leak between cases.
        final result = UrlScorer().score(url);

        expect(result.score, expectedScore, reason: 'score for $url');
        expect(result.level.label, expectedLevel, reason: 'level for $url');

        // Rule id 0 is the sentinel for notices that are not rules (the
        // allowlist bypass, and the unparseable-URL fallback), so it is
        // excluded from the rule-set comparison.
        final firedRules = result.findings
            .map((f) => f.ruleId)
            .where((id) => id > 0)
            .toSet()
            .toList()
          ..sort();
        expect(firedRules, expectedRules, reason: 'fired rules for $url');
      });
    }
  });

  group('TASK-038 regression guards', () {
    // These are real sites. A warning on any of them teaches students to
    // ignore warnings, which is worse than no product at all.
    const mustBeSafe = [
      'https://grambling.edu',
      'https://www.grambling.edu/admissions',
      'https://www.instagram.com',
      'https://www.grambling.edu/academics/colleges/college-of-business',
    ];

    for (final url in mustBeSafe) {
      test('$url is not flagged', () {
        expect(UrlScorer().score(url).level, RiskLevel.safe, reason: url);
      });
    }

    // The typosquat of the project's own university must stay HIGH RISK.
    // A rejected fix candidate (raising Rule 15's consonant threshold to
    // 0.80) downgraded this to SUSPICIOUS, which is why it was rejected.
    test('grarnbling.edu typosquat stays HIGH RISK', () {
      final result = UrlScorer().score('https://grarnbling.edu/student/login');
      expect(result.level, RiskLevel.highRisk);
    });
  });

  group('verdict thresholds', () {
    test('0-2 is safe, 3-5 suspicious, 6+ high risk', () {
      expect(RiskLevel.fromScore(0), RiskLevel.safe);
      expect(RiskLevel.fromScore(2), RiskLevel.safe);
      expect(RiskLevel.fromScore(3), RiskLevel.suspicious);
      expect(RiskLevel.fromScore(5), RiskLevel.suspicious);
      expect(RiskLevel.fromScore(6), RiskLevel.highRisk);
      expect(RiskLevel.fromScore(99), RiskLevel.highRisk);
    });
  });

  group('Rule 20 SimHash near-duplicate detection', () {
    test('does not fire on the first sighting of a URL', () {
      final result = UrlScorer().score('https://example.com/alpha');
      expect(result.findings.where((f) => f.ruleId == 20), isEmpty);
    });

    test('fires on a structurally near-identical URL later in the session', () {
      final scorer = UrlScorer();
      scorer.score('https://example.com/promo/landing?ref=a');
      final second = scorer.score('https://example.com/promo/landing?ref=b');
      expect(second.findings.where((f) => f.ruleId == 20), isNotEmpty);
    });

    test('is scoped to one scorer, so sessions cannot leak into each other', () {
      UrlScorer().score('https://example.com/promo/landing?ref=a');
      final other = UrlScorer().score('https://example.com/promo/landing?ref=b');
      expect(other.findings.where((f) => f.ruleId == 20), isEmpty);
    });
  });

  group('LCS similarity', () {
    test('is 1.0 for identical strings and 0.0 when either side is empty', () {
      expect(lcsSimilarity('paypal', 'paypal'), 1.0);
      expect(lcsSimilarity('', 'paypal'), 0.0);
      expect(lcsSimilarity('paypal', ''), 0.0);
    });

    test('rates a homoglyph swap above the 0.75 typosquatting threshold', () {
      expect(lcsSimilarity('paypa1', 'paypal'), greaterThanOrEqualTo(0.75));
    });

    test('rates unrelated brands below the threshold', () {
      expect(lcsSimilarity('netflix', 'chase'), lessThan(0.75));
    });
  });

  group('apex domain extraction', () {
    test('handles two-part TLDs', () {
      expect(apexDomain('amaz0n.co.uk'), 'amaz0n');
      expect(apexDomain('login.paypa1.com'), 'paypa1');
      expect(apexDomain('example.com'), 'example');
    });
  });

  group('SimHash fingerprints', () {
    test('are stable for the same URL', () {
      expect(simHash('https://example.com/a'), simHash('https://example.com/a'));
    });

    test('put structurally different URLs far apart', () {
      final a = simHash('https://example.com/alpha');
      final b = simHash('https://completely-different.org/zulu/x/y?q=1');
      expect(hammingDistance(a, b), greaterThan(simHashThreshold));
    });
  });
}
