"""Turn tool/parity_corpus.json into test/url_scorer_test.dart.

Run generate_parity_corpus.py first — this reads its output. Paths resolve
relative to this file, so the two stay chained no matter where you run them
from.

Usage (from scansafe-mobile):
    python tool/generate_parity_test.py
"""

import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
CORPUS = os.path.join(HERE, "parity_corpus.json")
DEST = os.path.join(PROJECT, "test", "url_scorer_test.dart")


def dq(value):
    """Quote a Python string as a Dart single-quoted literal."""
    escaped = (
        value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("$", r"\$")  # Dart interpolates $ inside single quotes
    )
    return "'" + escaped + "'"


def main():
    corpus = json.load(io.open(CORPUS, encoding="utf-8"))

    rows = "\n".join(
        "  (%s, %d, %s, %s)," % (
            dq(entry["url"]),
            entry["score"],
            dq(entry["level"]),
            "[" + ", ".join(str(r) for r in entry["rules"]) + "]",
        )
        for entry in corpus
    )

    out = TEMPLATE.replace("__ROWS__", rows)
    io.open(DEST, "w", encoding="utf-8", newline="\n").write(out)
    print("wrote %d parity cases to %s" % (len(corpus), os.path.relpath(DEST, PROJECT)))


TEMPLATE = r'''import 'package:flutter_test/flutter_test.dart';
import 'package:scansafe/core/fuzzy.dart';
import 'package:scansafe/core/risk_level.dart';
import 'package:scansafe/core/url_scorer.dart';

/// GENERATED by tool/generate_parity_test.py — do not edit by hand.
///
/// Ground truth comes from the Python research prototype
/// (scansafe_prototype.py), scored with a freshly cleared SimHash cache, plus
/// the deliberate divergences recorded in tool/generate_parity_corpus.py.
/// Each row is (url, expectedScore, expectedLevel, firedRules).
///
/// A failure here means the Dart engine drifted from the research artefact.
/// Fix the engine. Regenerating the corpus to turn a test green destroys the
/// evidence instead of the bug.
const List<(String, int, String, List<int>)> parityCorpus = [
__ROWS__
];

void main() {
  group('Dart engine matches the Python prototype', () {
    for (final (url, expectedScore, expectedLevel, expectedRules)
        in parityCorpus) {
      test('scores $url as $expectedScore ($expectedLevel)', () {
        // Fresh scorer per case mirrors clearing the prototype's global
        // SimHash cache, so Rule 20 cannot leak between cases.
        final result = UrlScorer().score(url);

        expect(result.score, expectedScore, reason: 'score for $url');
        expect(result.level.label, expectedLevel, reason: 'level for $url');

        // Rule id 0 is the sentinel for notices that are not rules (the
        // allowlist bypass, and the unparseable-URL fallback), so it is
        // excluded from the rule-set comparison.
        final firedRules = result.findings
            .map((f) => f.ruleId)
            .where((id) => id > 0)
            .toSet()
            .toList()
          ..sort();
        expect(firedRules, expectedRules, reason: 'fired rules for $url');
      });
    }
  });

  group('TASK-038 regression guards', () {
    // These are real sites. A warning on any of them teaches students to
    // ignore warnings, which is worse than no product at all.
    const mustBeSafe = [
      'https://grambling.edu',
      'https://www.grambling.edu/admissions',
      'https://www.instagram.com',
      'https://www.grambling.edu/academics/colleges/college-of-business',
    ];

    for (final url in mustBeSafe) {
      test('$url is not flagged', () {
        expect(UrlScorer().score(url).level, RiskLevel.safe, reason: url);
      });
    }

    // The typosquat of the project's own university must stay HIGH RISK.
    // A rejected fix candidate (raising Rule 15's consonant threshold to
    // 0.80) downgraded this to SUSPICIOUS, which is why it was rejected.
    test('grarnbling.edu typosquat stays HIGH RISK', () {
      final result = UrlScorer().score('https://grarnbling.edu/student/login');
      expect(result.level, RiskLevel.highRisk);
    });
  });

  group('verdict thresholds', () {
    test('0-2 is safe, 3-5 suspicious, 6+ high risk', () {
      expect(RiskLevel.fromScore(0), RiskLevel.safe);
      expect(RiskLevel.fromScore(2), RiskLevel.safe);
      expect(RiskLevel.fromScore(3), RiskLevel.suspicious);
      expect(RiskLevel.fromScore(5), RiskLevel.suspicious);
      expect(RiskLevel.fromScore(6), RiskLevel.highRisk);
      expect(RiskLevel.fromScore(99), RiskLevel.highRisk);
    });
  });

  group('Rule 20 SimHash near-duplicate detection', () {
    test('does not fire on the first sighting of a URL', () {
      final result = UrlScorer().score('https://example.com/alpha');
      expect(result.findings.where((f) => f.ruleId == 20), isEmpty);
    });

    test('fires on a structurally near-identical URL later in the session', () {
      final scorer = UrlScorer();
      scorer.score('https://example.com/promo/landing?ref=a');
      final second = scorer.score('https://example.com/promo/landing?ref=b');
      expect(second.findings.where((f) => f.ruleId == 20), isNotEmpty);
    });

    test('is scoped to one scorer, so sessions cannot leak into each other', () {
      UrlScorer().score('https://example.com/promo/landing?ref=a');
      final other = UrlScorer().score('https://example.com/promo/landing?ref=b');
      expect(other.findings.where((f) => f.ruleId == 20), isEmpty);
    });
  });

  group('LCS similarity', () {
    test('is 1.0 for identical strings and 0.0 when either side is empty', () {
      expect(lcsSimilarity('paypal', 'paypal'), 1.0);
      expect(lcsSimilarity('', 'paypal'), 0.0);
      expect(lcsSimilarity('paypal', ''), 0.0);
    });

    test('rates a homoglyph swap above the 0.75 typosquatting threshold', () {
      expect(lcsSimilarity('paypa1', 'paypal'), greaterThanOrEqualTo(0.75));
    });

    test('rates unrelated brands below the threshold', () {
      expect(lcsSimilarity('netflix', 'chase'), lessThan(0.75));
    });
  });

  group('apex domain extraction', () {
    test('handles two-part TLDs', () {
      expect(apexDomain('amaz0n.co.uk'), 'amaz0n');
      expect(apexDomain('login.paypa1.com'), 'paypa1');
      expect(apexDomain('example.com'), 'example');
    });
  });

  group('SimHash fingerprints', () {
    test('are stable for the same URL', () {
      expect(simHash('https://example.com/a'), simHash('https://example.com/a'));
    });

    test('put structurally different URLs far apart', () {
      final a = simHash('https://example.com/alpha');
      final b = simHash('https://completely-different.org/zulu/x/y?q=1');
      expect(hammingDistance(a, b), greaterThan(simHashThreshold));
    });
  });
}
'''

if __name__ == "__main__":
    main()
